define([
    './data/geometry/beaver',
    './data/geometry/boxelder',
    './data/geometry/cache',
    './data/geometry/carbon',
    './data/geometry/daggett',
    './data/geometry/davis',
    './data/geometry/duchesne',
    './data/geometry/emery',
    './data/geometry/garfield',
    './data/geometry/grand',
    './data/geometry/iron',
    './data/geometry/juab',
    './data/geometry/kane',
    './data/geometry/millard',
    './data/geometry/morgan',
    './data/geometry/piute',
    './data/geometry/rich',
    './data/geometry/saltlake',
    './data/geometry/sanjuan',
    './data/geometry/sanpete',
    './data/geometry/sevier',
    './data/geometry/summit',
    './data/geometry/tooele',
    './data/geometry/uintah',
    './data/geometry/utah',
    './data/geometry/wasatch',
    './data/geometry/washington',
    './data/geometry/wayne',
    './data/geometry/weber'
], function (
    beaver,
    boxelder,
    cache,
    carbon,
    daggett,
    davis,
    duchesne,
    emery,
    garfield,
    grand,
    iron,
    juab,
    kane,
    millard,
    morgan,
    piute,
    rich,
    saltlake,
    sanjuan,
    sanpete,
    sevier,
    summit,
    tooele,
    uintah,
    utah,
    wasatch,
    washington,
    wayne,
    weber
) {
    var geometryLookup = {
        beaver: beaver,
        boxelder: boxelder,
        cache: cache,
        carbon: carbon,
        daggett: daggett,
        davis: davis,
        duchesne: duchesne,
        emery: emery,
        garfield: garfield,
        grand: grand,
        iron: iron,
        juab: juab,
        kane: kane,
        millard: millard,
        morgan: morgan,
        piute: piute,
        rich: rich,
        saltlake: saltlake,
        sanjuan: sanjuan,
        sanpete: sanpete,
        sevier: sevier,
        summit: summit,
        tooele: tooele,
        uintah: uintah,
        utah: utah,
        wasatch: wasatch,
        washington: washington,
        wayne: wayne,
        weber: weber
    };

    var countyHelper = {
        countyList: function () {
            return [
                'beaver',
                'box elder',
                'cache',
                'carbon',
                'daggett',
                'davis',
                'duchesne',
                'emery',
                'garfield',
                'grand',
                'iron',
                'juab',
                'kane',
                'millard',
                'morgan',
                'piute',
                'rich',
                'salt lake',
                'san juan',
                'sanpete',
                'sevier',
                'summit',
                'tooele',
                'uintah',
                'utah',
                'wasatch',
                'washington',
                'wayne',
                'weber'
            ];
        },
        getGeometryFor: function (county) {
            county = county.toLowerCase().replace(/\s/g, '');

            return geometryLookup[county];
        }
    };

    return countyHelper;
});
